language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cd rhdlc/
  - cargo build
  - cargo test --features no-color -- --nocapture
cache:
  cargo: true
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
