name: rhdlc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Z3
        run: sudo apt-get install libz3-dev
      - name: Build
        run: cargo build
      - name: Install cargo-tarpaulin
        run: "cargo install cargo-tarpaulin -f"
      - name: Run cargo-tarpaulin
        run: "cargo tarpaulin --out Lcov --verbose --features no-color"
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
